// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkhxircgcysdzmofwnbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndraHhpcmNnY3lzZHptb2Z3bmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjE4MzAsImV4cCI6MjA3MDg5NzgzMH0.cqD-_AgzJbF5Gm_31r3OT0iGYb0QRkBS2ErtkOuyEdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});